import React, { useState } from 'react';
import { X, Check, Copy, Database, Server, Terminal, ExternalLink, Key } from 'lucide-react';
import { isSupabaseConfigured } from '../client';

export const SupabaseConfigModal = ({ isOpen, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const sqlCode = `-- Create crewmates table in Supabase SQL Editor
CREATE TABLE crewmates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  speed NUMERIC DEFAULT 1.0,
  color TEXT NOT NULL,
  category TEXT DEFAULT 'Engineering & Tech',
  role TEXT DEFAULT 'Warp Drive Engineer',
  weapon TEXT DEFAULT 'Hydro-Spanner',
  bio TEXT DEFAULT ''
);

-- Enable Row Level Security (RLS) or add public read/write policy
ALTER TABLE crewmates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public full access to crewmates"
ON crewmates
FOR ALL
USING (true)
WITH CHECK (true);
`;

  const copySql = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fadeIn">
      <div className="glass-panel max-w-2xl w-full p-6 sm:p-8 rounded-2xl relative border border-cyan-500/30 max-h-[90vh] overflow-y-auto">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-2 rounded-lg hover:bg-slate-800/60 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="w-12 h-12 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center">
            <Database className="w-6 h-6 text-cyan-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold font-heading text-white">Database Status & Supabase Setup</h2>
            <p className="text-xs text-slate-400">Manage your Supabase connection & table schema</p>
          </div>
        </div>

        {/* Status indicator */}
        <div className={`p-4 rounded-xl mb-6 border ${
          isSupabaseConfigured 
            ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' 
            : 'bg-amber-500/10 border-amber-500/30 text-amber-300'
        }`}>
          <div className="flex items-center gap-3">
            <Server className="w-5 h-5 flex-shrink-0" />
            <div>
              <p className="font-semibold text-sm">
                Status: {isSupabaseConfigured ? 'Supabase Database Connected' : 'Local Storage Mode Active'}
              </p>
              <p className="text-xs text-slate-300 mt-0.5">
                {isSupabaseConfigured
                  ? 'Your app is directly reading and writing to your live Supabase cloud database.'
                  : 'Currently storing crewmates in local browser database. Connect Supabase below to sync across cloud instances.'}
              </p>
            </div>
          </div>
        </div>

        {/* Setup Guide */}
        <div className="space-y-4">
          <h3 className="text-sm font-semibold font-heading text-cyan-400 tracking-wider flex items-center gap-2">
            <Key className="w-4 h-4" /> 1. SET UP SUPABASE ENVIRONMENT VARIABLES
          </h3>
          <div className="bg-[#050811] p-4 rounded-xl border border-slate-800 text-xs font-mono text-slate-300 space-y-1">
            <p className="text-slate-400"># Inside Crewmates/.env</p>
            <p><span className="text-cyan-400">VITE_SUPABASE_URL</span>=https://your-project.supabase.co</p>
            <p><span className="text-cyan-400">VITE_SUPABASE_KEY</span>=eyJhbGciOiJIUzI1NiIsIn... (anon key)</p>
          </div>

          <h3 className="text-sm font-semibold font-heading text-cyan-400 tracking-wider flex items-center gap-2 mt-6">
            <Terminal className="w-4 h-4" /> 2. SQL TABLE CREATION SCHEMA
          </h3>
          <p className="text-xs text-slate-400">
            Paste this SQL script into your Supabase project's <strong className="text-slate-200">SQL Editor</strong> tab to create the required <code className="text-cyan-400 font-mono">crewmates</code> table:
          </p>

          <div className="relative bg-[#050811] rounded-xl border border-slate-800 overflow-hidden">
            <button
              onClick={copySql}
              className="absolute top-3 right-3 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy SQL'}</span>
            </button>
            <pre className="p-4 text-xs font-mono text-cyan-300/90 overflow-x-auto leading-relaxed">
              {sqlCode}
            </pre>
          </div>
        </div>

        {/* Footer actions */}
        <div className="mt-8 pt-4 border-t border-slate-800/80 flex items-center justify-between">
          <a
            href="https://supabase.com/dashboard"
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-cyan-400 hover:text-cyan-300 flex items-center gap-1 font-semibold"
          >
            <span>Open Supabase Dashboard</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>

          <button
            onClick={onClose}
            className="btn-secondary text-xs py-2 px-5"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
